export const dataProducts=[
    {
        id: 1,
        title: "Hangover stew",
        // description: "Korean Foods",
        price: 350,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
        inCart:false,
        count:1
      },
      {
        id: 2,
        title: "Soft Tofu Stew ",
        // description: "Korean Foods",
        price: 250,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 3,
        title: "Samgyeopsal",
        // description: "Korean Foods",
        price: 350,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb:'../images/s2.jpg',
      },
    
      {
        id: 4,
        title: "Chimaek",
        // description: "Korean Foods",
        price: 600,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 5,
        title: "Kimchi Stew",
        // description: "Korean Foods",
        price: 1250,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 6,
        title: "Instant noodles",
        // description: "Chinese Foods",
        price: 499,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 7,
        title: "RBraised Pork Balls in Gravy",
        // description: "Chinese Foods",
        price: 699,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 8,
        title: "Dumplings",
        // description: "Chinese Foods",
        price: 299,
        // currency: "Rs",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 9,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 1499,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 10,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 1999,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 11,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 999,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 12,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 890,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 13,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 400,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 14,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 250,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
      {
        id: 15,
        title: "Steamed momos",
        // description: "Chinese Foods",
        price: 150,
        // currency: "RS",
        inCart:false,
        count:1,
        thumb: '../images/s2.jpg',
      },
    ];
    